// The built-in things to rate in a profile, for pod members only: like
// lib/ideas-data.ts, import this only from app/api/ideas, never from anything
// that runs in the browser (`npm run check:bundle` checks). Ids are fixed
// (ratings are kept against them); add new ones at the end of a section, and
// never reuse or renumber one.

import type { RateSection } from './menu';

const s = (key: string, title: string, items: string[]): RateSection =>
  ({ id: `bi-${key}`, title, items: items.map((label, i) => ({ id: `bi-${key}-${String(i + 1).padStart(2, '0')}`, label })) });

export function builtInInventory(): RateSection[] {
  return [
    s('touch', 'Touch & senses', [
      'Slow kissing, no rush',
      'Kisses on the neck and ears',
      'Light scratching',
      'Gentle biting',
      'Marks that show (hickeys, bites)',
      'Hair pulling',
      'Wrists held down',
      'A full-body massage',
      'Foot massage or worship',
      'Ice or cold on the skin',
      'Warm massage oil',
      'Feathers and soft things, blindfolded',
      'Teasing without finishing',
      'Whispered dirty talk',
      'Being loud',
      'An hour of touch, taking it slow',
      'Showering together',
      'Playful spanking',
    ]),
    s('gear', 'Toys, gear & dressing up', [
      'A vibrator together',
      'A remote-controlled toy, at home',
      'A blindfold',
      'Soft restraints (silk, scarves)',
      'Cuffs (leather or metal)',
      'Rope, simple ties',
      'A paddle or crop',
      'Low-temperature wax',
      'Lingerie the other one chose',
      'Heels in bed',
      'A costume or uniform',
      'A collar, at home',
      'A plug or anal toy',
      'A strap-on',
      'Photos or video, just for the two of you',
      'Mirrors',
    ]),
    s('power', 'Power & control', [
      'Setting the pace',
      'Handing over the pace',
      'Titles (Sir, Mistress, Ma’am…)',
      'Rules for the day',
      'Tasks to earn rewards',
      'Punishments for broken rules',
      'Kneeling',
      'Serving (drinks, food, a bath)',
      'Being told what to wear',
      'Being posed or moved',
      'Holding a position until allowed',
      'Asking permission to come',
      'Orgasm denial or chastity',
      'Being used for the other’s pleasure',
      'Worship (body, feet)',
      'Praise (“good girl”, “good boy”)',
      'Switching who’s in charge',
      'Long, slow aftercare',
    ]),
    s('kink', 'Kink', [
      'Bratting (acting up to be put in your place)',
      'Firm spanking',
      'Overstimulation',
      'Edging',
      'Light humiliation',
      'Name-calling (agreed words only)',
      'Blindfold and earplugs together',
      'Primal play (chasing, wrestling, pinning)',
      'Being woken with touch (agreed beforehand)',
      'Scripted reluctance, with a safeword',
      'A hand on the throat, no pressure',
      'Messy play (whipped cream, oil)',
      'Watching the other touch themselves',
      'Being watched touching yourself',
      'Characters (a boss, a stranger…)',
      'Anal play',
      'Toys during sex',
      'Sexting through the day',
    ]),
    s('out', 'Out & about, and fantasies', [
      'Flirting while out, home to finish',
      'Secret touching under the table',
      'No underwear on a date',
      'Instructions by text while apart',
      'A hotel afternoon',
      'Strangers meeting at a bar',
      'Watching porn together',
      'Talking through a fantasy, no plans to act',
      'A threesome (to talk about)',
      'A club, just to watch',
      'Being watched, somewhere made for it',
      'A sex-positive party',
      'A hotwife or hot-husband dynamic (to talk about)',
      'Swapping partners (to talk about)',
    ]),
  ];
}
